on: [push]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: OWASP ZAP
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
